### ISSUE TITLE
The InputMap action deson't exist

### ISSUE THREAD

**Issue by alexeychikk** [dazKind/squash-the-creeps-3d-hxgodot#3]
I'm sorry for the noob question. I'm following the [STC tutorial](https://docs.godotengine.org/en/stable/getting_started/first_3d_game/03.player_movement_code.html) but using hxgodot.
I've added the actions `move_right`, `move_left`, `move_forward`, `move_back` to the project's Input Map.
https://github.com/alexeychikk/hx-godot-squash-the-creeps/blob/main/project.godot#L24-L57
And in the HxPlayer I'm doing basically the same thing as in your code
https://github.com/alexeychikk/hx-godot-squash-the-creeps/blob/main/src/stc3d/HxPlayer.hx#L32-L43
But in the Godot editor I see multiple errors like these:
```
  The InputMap action "move_right" doesn't exist. Did you mean "ui_right"?
  The InputMap action "move_left" doesn't exist. Did you mean "ui_left"?
  The InputMap action "move_back" doesn't exist. Did you mean "ui_text_backspace"?
  The InputMap action "move_forward" doesn't exist.
```

Any idea why this may be happening?

**Comment by alexeychikk** [comment]
Answering my own question, this does the trick:
```haxe
    if (godot.Engine.singleton().is_editor_hint()) // skip if in editor
      return;
```

**Comment by dazKind** [comment]
Hi @alexeychikk 
yeah you are right. I think I missed the editor guards in the sample there. I might need to patch this.

**Comment by alexeychikk** [comment]
@dazKind This guard is present in your sample. I just followed the tutorial from the official godot docs and they do not add this check, which is odd.

**Comment by dazKind** [comment]
Ah I see. If you want you can join our discord channel here: https://discord.com/channels/162395145352904705/1059447388047159399
