### ISSUE TITLE
I cant enter the game

### ISSUE THREAD

**Issue by gerroon** [dazKind/squash-the-creeps-3d-hxgodot#4]
Hi

I installed hxgodot and Godot 4.2.1 on Windows. I compiled the game according to the readme. I can start the game but I cant pass the "press enter to retry" screen. This text shows up the second the game load and not passeable it seems. I tried all kinds of keys obviously including the "enter" key

This is what I used to build the bindings

`scons platform=windows target=release`

I also get this error when I stop the game, not sure if it is related

```
--- Debugging process stopped ---
  core/extension/gdextension.cpp:688 - GDExtension library not found: 
  Failed loading resource: res://stc3d.gdextension. Make sure resources have been imported by opening the project in the editor at least once.

```

![image](https://github.com/HxGodot/squash-the-creeps-3d-hxgodot/assets/8519469/af110411-fc7b-483d-8c89-fa01a5410afe)

**Comment by dazKind** [comment]
HI gerron,

try building the debug version: `scons platform=windows target=debug`. 

When you start the editor, it will try to load the debug version of the extension which is specified [here](https://github.com/HxGodot/squash-the-creeps-3d-hxgodot/blob/main/stc3d.gdextension#L18). The release version of the extension will be used when you export your game to be standalone

**Comment by gerroon** [comment]
That works, thank you!!!!!!

**Comment by dazKind** [comment]
You're welcome :)
